# Использование базового образа Python
   FROM python:3.12-slim

   # Устанавка рабочей директории
   WORKDIR /app

   # Копирование всех файлов в контейнер
   COPY . .

   # Устанавка зависимости
   RUN pip install --no-cache-dir -r requirements.txt

   # Команда для запуска приложения
   CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
